apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitterclone
  labels:
    app: twitterclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitterclone
  template:
    metadata:
      labels:
        app: twitterclone
    spec:
      containers:
      - name: twitteruserservice
        image: semm12/twitteruserservice
        imagePullPolicy: Always
        ports:
          - containerPort: 8090
      - name: twittertweetservice
        image: semm12/twittertweetservice
        imagePullPolicy: Always
        ports:
          - containerPort: 8082
      - name: twitterauthservice
        image: semm12/twitterauthservice
        imagePullPolicy: Always
        ports:
          - containerPort: 8091
      - name: twitterapigateway
        image: semm12/twitterapigateway
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
