apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitterclone
  labels:
    app: twitterclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitterclone
  template:
    metadata:
      labels:
        app: twitterclone
    spec:
      containers:
      - name: twitteruserservice
        image: semm12/twitteruserservice:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8090
      - name: api-gateway
        image: semm12/twitterapigateway:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
