apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: twitterclone
spec:
  selector:
    app: twitterclone
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
